logo_title: cmkk 请叫我康康

style: black

favicon: /k.svg

menu:
  作品: /works
  # 域名: /domain
  友联: /links
  关于: /about
  待办: /todos
  Github: https://github.com/cmkangkang

footer:
  copyright: cmkk
  url: https://cmkangkang.github.io/
  icp: 黔ICP备2021005921号-1
  domain: https://beian.miit.gov.cn

gitalk:
  enable: true
  clientID: 6d20197ba953a4b4a688
  clientSecret: fe5d9ec0315a32e40a86f055cc5c30804aaae82a
  repo: cmkangkang.github.io
  owner: cmKangkang
  admin: cmKangkang

highlight:
  enable: false